#!/bin/sh
EXTRA_ARGS=$@

cmake -D CMAKE_INSTALL_PREFIX:PATH=../paraview-install \
	-D PARAVIEW_USE_MPI:BOOL=ON \
	-D PARAVIEW_ENABLE_PYTHON:BOOL=ON \
	-D PARAVIEW_INSTALL_DEVELOPMENT_FILES:BOOL=ON \
	-D OPENGL_INCLUDE_DIR:PATH=${MesaDIR}/include \
	-D OPENGL_gl_LIBRARY:PATH=${MesaDIR}/lib/libGL.so \
	-D OPENGL_glu_LIBRARY:PATH=${MesaDIR}/lib/libGLU.so \
	-D VTK_OPENGL_HAS_OSMESA:BOOL=ON \
	-D OSMESA_INCLUDE_DIR:PATH=${MesaDIR}/include \
	-D OSMESA_LIBRARY:PATH=${MesaLIB} \
	${ParaViewSrcDir}
